SELECT T_ADHERENTS.nom,T_MESSAGE.message
FROM T_ADHERENTS,T_MESSAGES
WHERE T_ADHERENTS.id=T_MESSAGES.id_adherent
AND T_ADHERENTS.nom = 'Machin';


SELECT T_ADHERENT.nom, T_MESSAGES.texte
FROM T_ADHERENTS
LEFT JOIN T_MESSAGES ON T_ADHERENTS.id=T_MESSAGES
WHERE T_ADHERENTS.nom = 'Michel';